In [5]:
!pip install mysql-connector-python
#he ! tells Jupyter to run the command in your system's terminal rather than as Python code.

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/480.6 kB ? eta -:--:--
   - ------------------------------------- 20.5/480.6 kB 640.0 kB/s eta 0:00:01
   ------- -------------------------------- 92.2/480.6 kB 1.7 MB/s eta 0:00:01
   ------------------------- -------------- 307.2/480.6 kB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 450.6/480.6 kB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 480.6/480.6 kB 2.5 MB/s eta 0:00:00


In [7]:
# loading mconnector
import mysql.connector

In [19]:
#connection of database
my_db=mysql.connector.connect(host="localhost",user = 'root',passwd="abc11")

In [11]:
#create cursor
my_cursor =my_db.cursor()

In [13]:
# having a glance at databases
my_cursor.execute('show databases')

In [17]:
for i in my_cursor:
    print(i)


('adventureworks2022',)
('college',)
('commodity_db',)
('exercise',)
('hr',)
('imdb',)
('information_schema',)
('intvu',)
('kkk',)
('learn1',)
('market_star_schema',)
('mydatabase',)
('mynewdb',)
('mysql',)
('performance_schema',)
('retail_db',)
('salesdb',)
('supply_db',)
('sys',)
('test',)
('testdb',)
('upgrade',)
('world',)
('xyz_company',)


In [29]:
my_db=mysql.connector.connect(host="localhost",user = 'root',passwd="abc11", database='college')

In [33]:
#create cursor
my_cursor =my_db.cursor()

In [35]:
# having a glance at databases
my_cursor.execute('show tables')

In [37]:
for i in my_cursor:
    print(i)

('student',)


In [39]:
my_cursor.execute('select * from student')
for i in my_cursor:
    print(i)

(101, 'anil', 78, 'C', 'Pune')
(102, 'Bhumika', 93, 'A', 'Mumbai')
(103, 'Chetan', 85, 'B', 'Mumbai')
(104, 'rahul', 85, 'B', 'Delhi')
(105, 'Dhruv', 12, 'F', 'Delhi')
(106, 'Farah', 82, 'B', 'Delhi')


In [53]:
# insert record
sql = "insert into student(rollno,name,marks,grade,city) values(110, 'Ramesh', 88, 'A', 'Bihar')"
my_cursor.execute(sql)

# Commit the transaction to save changes to the database
my_db.commit()

In [55]:
my_cursor.execute('select * from student')
for i in my_cursor:
    print(i)

(101, 'anil', 78, 'C', 'Pune')
(102, 'Bhumika', 93, 'A', 'Mumbai')
(103, 'Chetan', 85, 'B', 'Mumbai')
(104, 'rahul', 85, 'B', 'Delhi')
(105, 'Dhruv', 12, 'F', 'Delhi')
(106, 'Farah', 82, 'B', 'Delhi')
(110, 'Ramesh', 88, 'A', 'Bihar')


### To insert multiple rows into your MySQL table at once, 
you should use the **executemany()** method instead of **execute()**.

This is much more efficient than running a single INSERT statement over and over again in a loop.

Here is how you can do it right in your Jupyter Notebook:

Why use this approach?
**%s Placeholder**: These act as secure placeholders for your data. The connector automatically handles adding the single quotes around strings (like 'Patna' or 'Priya'), which prevents the syntax errors you ran into earlier.

**my_cursor.rowcount**: This is a handy property that will output exactly how many rows were just added to your student table.

In [57]:
# 1. Define the SQL query with placeholders (%s)
sql = "INSERT INTO student (rollno, name, marks, grade, city) VALUES (%s, %s, %s, %s, %s)"

# 2. Prepare a list of tuples containing your data
data = [
    (111, 'Siddharth', 90, 'A', 'Patna'),
    (112, 'Priya', 85, 'B', 'Ranchi'),
    (113, 'Amit', 72, 'C', 'Gaya'),
    (114, 'Neha', 95, 'A', 'Muzaffarpur')
]

# 3. Use executemany to insert all rows at once
my_cursor.executemany(sql, data)

# 4. Commit the transaction to save changes
my_db.commit()

print(f"{my_cursor.rowcount} records inserted successfully.")

4 records inserted successfully.


In [59]:
my_cursor.execute('select * from student')
for i in my_cursor:
    print(i)

(101, 'anil', 78, 'C', 'Pune')
(102, 'Bhumika', 93, 'A', 'Mumbai')
(103, 'Chetan', 85, 'B', 'Mumbai')
(104, 'rahul', 85, 'B', 'Delhi')
(105, 'Dhruv', 12, 'F', 'Delhi')
(106, 'Farah', 82, 'B', 'Delhi')
(110, 'Ramesh', 88, 'A', 'Bihar')
(111, 'Siddharth', 90, 'A', 'Patna')
(112, 'Priya', 85, 'B', 'Ranchi')
(113, 'Amit', 72, 'C', 'Gaya')
(114, 'Neha', 95, 'A', 'Muzaffarpur')


To delete records from your table, you use the SQL DELETE FROM statement. Just like with inserting data, it is highly recommended to use placeholders (%s) to specify which record(s) you want to remove. This prevents accidental syntax errors and protects against SQL injection.

Here are the two ways you can handle deletions in your Jupyter Notebook:

1. Delete a Single Specific Record
If you want to delete one specific student (for example, the student with rollno = 110), use this code:

In [61]:
# Define the delete query with a placeholder
sql = "DELETE FROM student WHERE rollno = %s"

# Provide the value as a tuple (note the comma at the end for a single value tuple)
data = (110,)

# Execute and commit
my_cursor.execute(sql, data)
my_db.commit()

print(f"{my_cursor.rowcount} record(s) deleted.")

1 record(s) deleted.


In [63]:
my_cursor.execute('select * from student')
for i in my_cursor:
    print(i)

(101, 'anil', 78, 'C', 'Pune')
(102, 'Bhumika', 93, 'A', 'Mumbai')
(103, 'Chetan', 85, 'B', 'Mumbai')
(104, 'rahul', 85, 'B', 'Delhi')
(105, 'Dhruv', 12, 'F', 'Delhi')
(106, 'Farah', 82, 'B', 'Delhi')
(111, 'Siddharth', 90, 'A', 'Patna')
(112, 'Priya', 85, 'B', 'Ranchi')
(113, 'Amit', 72, 'C', 'Gaya')
(114, 'Neha', 95, 'A', 'Muzaffarpur')


2. Delete Multiple Specific Records
If you want to delete multiple specific rows at once (for example, removing students with roll numbers 111 and 112), you can pair your query with executemany():

In [65]:
# Define the delete query
sql = "DELETE FROM student WHERE rollno = %s"

# List of tuples containing the roll numbers to delete
data = [
    (111,),
    (112,)
]

# Execute multi-delete and commit
my_cursor.executemany(sql, data)
my_db.commit()

print(f"{my_cursor.rowcount} record(s) deleted.")

2 record(s) deleted.


In [67]:
my_cursor.execute('select * from student')
for i in my_cursor:
    print(i)

(101, 'anil', 78, 'C', 'Pune')
(102, 'Bhumika', 93, 'A', 'Mumbai')
(103, 'Chetan', 85, 'B', 'Mumbai')
(104, 'rahul', 85, 'B', 'Delhi')
(105, 'Dhruv', 12, 'F', 'Delhi')
(106, 'Farah', 82, 'B', 'Delhi')
(113, 'Amit', 72, 'C', 'Gaya')
(114, 'Neha', 95, 'A', 'Muzaffarpur')


To update existing records in your table, you use the SQL UPDATE statement. Just like with inserting and deleting, using %s placeholders is the best practice to safely pass your data.

Here is how you can update a record (for example, updating a student's marks and grade based on their roll number) in your Jupyter Notebook:

1. Update a Single Record

In [69]:
# 1. Define the UPDATE query with placeholders
sql = "UPDATE student SET marks = %s, grade = %s WHERE rollno = %s"

# 2. Provide the new values and the matching condition (New Marks, New Grade, Roll No)
data = (95, 'A', 101)

# 3. Execute and commit the changes
my_cursor.execute(sql, data)
my_db.commit()

print(f"{my_cursor.rowcount} record(s) updated successfully.")

1 record(s) updated successfully.


In [71]:
my_cursor.execute('select * from student')
for i in my_cursor:
    print(i)

(101, 'anil', 95, 'A', 'Pune')
(102, 'Bhumika', 93, 'A', 'Mumbai')
(103, 'Chetan', 85, 'B', 'Mumbai')
(104, 'rahul', 85, 'B', 'Delhi')
(105, 'Dhruv', 12, 'F', 'Delhi')
(106, 'Farah', 82, 'B', 'Delhi')
(113, 'Amit', 72, 'C', 'Gaya')
(114, 'Neha', 95, 'A', 'Muzaffarpur')


2. Update Multiple Records at Once
If you have a list of multiple students whose records need to be updated, you can pair the UPDATE statement with executemany():

In [73]:
# Define the query
sql = "UPDATE student SET marks = %s, grade = %s WHERE rollno = %s"

# List of tuples: [(New Marks, New Grade, Roll No), ...]
data = [
    (88, 'B', 104),
    (45, 'A', 105),  # Giving Dhruv a massive grace-mark update!
    (90, 'A', 106)
]

# Execute batch update and commit
my_cursor.executemany(sql, data)
my_db.commit()

print(f"{my_cursor.rowcount} records updated successfully.")

3 records updated successfully.


In [75]:
my_cursor.execute('select * from student')
for i in my_cursor:
    print(i)

(101, 'anil', 95, 'A', 'Pune')
(102, 'Bhumika', 93, 'A', 'Mumbai')
(103, 'Chetan', 85, 'B', 'Mumbai')
(104, 'rahul', 88, 'B', 'Delhi')
(105, 'Dhruv', 45, 'A', 'Delhi')
(106, 'Farah', 90, 'A', 'Delhi')
(113, 'Amit', 72, 'C', 'Gaya')
(114, 'Neha', 95, 'A', 'Muzaffarpur')


### 1. Install SQLAlchemy (if you haven't already)
Run this command in a notebook cell to install SQLAlchemy:

In [77]:
!pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable


### 2. Reading SQL Data into a Pandas DataFrame
To pull your student table data into Pandas, use create_engine from SQLAlchemy to establish the connection, and then use pd.read_sql():

In [79]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Create a database connection engine
# Format: mysql+mysqlconnector://username:password@host/database_name
engine = create_engine("mysql+mysqlconnector://root:abc11@localhost/college")

# 2. Write your SQL Query
query = "SELECT * FROM student"

# 3. Load the data into a Pandas DataFrame
df = pd.read_sql(query, con=engine)

# Display the DataFrame
df

,rollno,name,marks,grade,city
0,101,anil,95,A,Pune
1,102,Bhumika,93,A,Mumbai
2,103,Chetan,85,B,Mumbai
3,104,rahul,88,B,Delhi
4,105,Dhruv,45,A,Delhi
5,106,Farah,90,A,Delhi
6,113,Amit,72,C,Gaya
7,114,Neha,95,A,Muzaffarpur


### 3. Writing a Pandas DataFrame back to a SQL Table
If you have data in a Pandas DataFrame and want to save it as a new table (or append it to an existing table) in your MySQL database, you use .to_sql():

In [81]:
# Sample DataFrame to send to MySQL
new_data = pd.DataFrame({
    'rollno': [115, 116],
    'name': ['Karan', 'Sneha'],
    'marks': [82, 91],
    'grade': ['B', 'A'],
    'city': ['Ranchi', 'Patna']
})

# Write the DataFrame to a SQL table named 'student'
# if_exists='append' will add the rows without deleting existing data
new_data.to_sql(name='student', con=engine, if_exists='append', index=False)

print("Data successfully written to MySQL!")

Data successfully written to MySQL!


In [92]:
engine = create_engine("mysql+mysqlconnector://root:abc11@localhost/commodity_db")

# 2. Write your SQL Query
query1 = "SELECT * FROM commodities_info"
query2 = "SELECT * FROM price_details"
query3 = "SELECT * FROM region_info"
# 3. Load the data into a Pandas DataFrame
df1 = pd.read_sql(query1, con=engine)
df2 = pd.read_sql(query2, con=engine)
df3 = pd.read_sql(query3, con=engine)
# Display the DataFrame


In [94]:
df1.head()

,Id,Commodity,Variety,Unit,Category
0,03t7,Moong,Split,Kg.,Food
1,04b3,Mustard Oil,,Kg/Litre,Food
2,0ox3,Onion,Regular,Kg.,Food
3,0x4p,Potato,Regular,Kg.,Food
4,10ck,Ragi,Regular,Kg.,Food


In [96]:
df2.head()

,Id,Region_Id,Commodity_Id,Date,Retail_Price
0,1,1,03t7,2019-01-01,90.0
1,2,2,03t7,2019-01-01,84.0
2,3,3,03t7,2019-01-01,85.0
3,4,4,03t7,2019-01-01,90.0
4,5,6,03t7,2019-01-01,77.0


In [98]:
df3.head()

,Id,Centre,State
0,1,Chittoor,Andhra Pradesh
1,2,Guntur,Andhra Pradesh
2,3,Kurnool,Andhra Pradesh
3,4,Vishakhapatnam,Andhra Pradesh
4,5,Itanagar,Arunachal Pradesh
